import { Routes } from '@angular/router';
import { ShellComponent } from './shared/layouts/admin-shell/shell.component';
import { PublicShellComponent } from './shared/layouts/public-shell/public-shell.component';
import { ComingSoonComponent } from './shared/components/coming-soon/coming-soon.component';
import { setPortalRole } from './core/guards/portal-role.guard';

/**
 * Public marketing pages now own the root route, while the existing
 * authentication and admin dashboard modules remain intact.
 */
export const routes: Routes = [
  {
    path: '',
    component: PublicShellComponent,
    children: [
      { path: '', title: "TransportSeva | India's Trusted Transport & Logistics Platform", loadComponent: () => import('./features/public/home/home.component').then((m) => m.HomeComponent) },
      { path: 'about', title: 'About Us | TransportSeva', loadComponent: () => import('./features/public/about/about.component').then((m) => m.AboutComponent) },
      { path: 'pricing', title: 'Pricing | TransportSeva', loadComponent: () => import('./features/public/pricing/pricing.component').then((m) => m.PricingComponent) },
      { path: 'contact', title: 'Contact Us | TransportSeva', loadComponent: () => import('./features/public/contact/contact.component').then((m) => m.ContactComponent) },
      { path: 'blog', title: 'Blog & Media | TransportSeva', loadComponent: () => import('./features/public/blog/blog.component').then((m) => m.BlogComponent) },
      { path: 'blog-post', title: 'How AI is Transforming Freight Route Optimization in India | TransportSeva', loadComponent: () => import('./features/public/blog-post/blog-post.component').then((m) => m.BlogPostComponent) },
      { path: 'careers', title: 'Careers | TransportSeva', loadComponent: () => import('./features/public/careers/careers.component').then((m) => m.CareersComponent) },
      { path: 'help-center', title: 'Help Center | TransportSeva', loadComponent: () => import('./features/public/help-center/help-center.component').then((m) => m.HelpCenterComponent) },
      { path: 'privacy-policy', title: 'Privacy Policy | TransportSeva', loadComponent: () => import('./features/public/privacy-policy/privacy-policy.component').then((m) => m.PrivacyPolicyComponent) },
      { path: 'terms-conditions', title: 'Terms & Conditions | TransportSeva', loadComponent: () => import('./features/public/terms-conditions/terms-conditions.component').then((m) => m.TermsConditionsComponent) },
      { path: 'refund-policy', title: 'Refund & Cancellation Policy | TransportSeva', loadComponent: () => import('./features/public/refund-policy/refund-policy.component').then((m) => m.RefundPolicyComponent) },
    ],
  },
  {
    path: 'auth',
    children: [
      { path: '', redirectTo: 'login', pathMatch: 'full' },
      { path: 'login', title: 'Log In | TransportSeva', loadComponent: () => import('./features/auth/login/login.component').then((m) => m.LoginComponent) },
      { path: 'signup', title: 'Sign Up | TransportSeva', loadComponent: () => import('./features/auth/signup/signup.component').then((m) => m.SignupComponent) },
      { path: 'otp-verification', title: 'OTP Verification | TransportSeva', loadComponent: () => import('./features/auth/otp-verification/otp-verification.component').then((m) => m.OtpVerificationComponent) },
      { path: 'forgot-password', title: 'Forgot Password | TransportSeva', loadComponent: () => import('./features/auth/forgot-password/forgot-password.component').then((m) => m.ForgotPasswordComponent) },
      { path: 'business-registration', title: 'Business Registration | TransportSeva', loadComponent: () => import('./features/auth/business-registration/business-registration.component').then((m) => m.BusinessRegistrationComponent) },
      { path: 'workspace-selection', title: 'Workspace Selection | TransportSeva', loadComponent: () => import('./features/auth/workspace-selection/workspace-selection.component').then((m) => m.WorkspaceSelectionComponent) },
      { path: 'profile-setup', title: 'Profile Setup | TransportSeva', loadComponent: () => import('./features/auth/profile-setup/profile-setup.component').then((m) => m.ProfileSetupComponent) },
    ],
  },
  {
    path: 'admin',
    component: ShellComponent,
    canActivate: [setPortalRole('admin')],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', title: 'TransportSeva | Admin Console', loadComponent: () => import('./features/dashboard/dashboard.component').then((m) => m.DashboardComponent) },
      { path: 'devices', title: 'Device Inventory | Admin Console | TransportSeva', loadComponent: () => import('./features/gps/device-inventory/device-inventory.component').then((m) => m.DeviceInventoryComponent) },
      { path: 'devices/:id', title: 'Device Details | Admin Console | TransportSeva', loadComponent: () => import('./features/gps/device-details/device-details.component').then((m) => m.DeviceDetailsComponent) },
      { path: 'tracking', title: 'Live Tracking | Admin Console | TransportSeva', loadComponent: () => import('./features/gps/live-tracking/live-tracking.component').then((m) => m.LiveTrackingComponent) },
      { path: 'trips', title: 'Trips | Admin Console | TransportSeva', loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trips/:id', title: 'Trip Details | Admin Console | TransportSeva', loadComponent: () => import('./features/trips/trip-details/trip-details.component').then((m) => m.TripDetailsComponent) },
      { path: 'wallet', title: 'Wallet | Admin Console | TransportSeva', loadComponent: () => import('./features/wallet/wallet.component').then((m) => m.WalletComponent) },
      { path: 'payments', title: 'Payments | Admin Console | TransportSeva', loadComponent: () => import('./features/payments/payments.component').then((m) => m.PaymentsComponent) },
      { path: 'reports', title: 'Reports & Analytics | Admin Console | TransportSeva', loadComponent: () => import('./features/reports/reports.component').then((m) => m.ReportsComponent) },
      { path: 'documents', title: 'Document Verification | Admin Console | TransportSeva', loadComponent: () => import('./features/documents/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'notifications', title: 'Notifications | Admin Console | TransportSeva', loadComponent: () => import('./features/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'support', title: 'Support | Admin Console | TransportSeva', loadComponent: () => import('./features/support/support.component').then((m) => m.SupportComponent) },
      { path: '**', title: 'TransportSeva | Admin Console', component: ComingSoonComponent },
    ],
  },
  {
    path: 'shipper',
    component: ShellComponent,
    canActivate: [setPortalRole('shipper')],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', title: 'Dashboard | Shipper Portal | TransportSeva', loadComponent: () => import('./features/shipper/dashboard/shipper-dashboard.component').then((m) => m.ShipperDashboardComponent) },
      { path: 'post-load', title: 'Post a Load | Shipper Portal | TransportSeva', loadComponent: () => import('./features/marketplace/post-load/post-load.component').then((m) => m.PostLoadComponent) },
      { path: 'my-loads', title: 'My Loads | Shipper Portal | TransportSeva', loadComponent: () => import('./features/marketplace/my-loads/my-loads.component').then((m) => m.MyLoadsComponent) },
      { path: 'load-board/:id', title: 'Load Details | Shipper Portal | TransportSeva', loadComponent: () => import('./features/marketplace/load-details/load-details.component').then((m) => m.LoadDetailsComponent) },
      { path: 'applications', title: 'Applications Received | Shipper Portal | TransportSeva', loadComponent: () => import('./features/marketplace/applications/applications.component').then((m) => m.ApplicationsComponent) },
      { path: 'bookings', title: 'Bookings | Shipper Portal | TransportSeva', loadComponent: () => import('./features/marketplace/bookings/bookings.component').then((m) => m.BookingsComponent) },
      { path: 'tracking', title: 'Live Tracking | Shipper Portal | TransportSeva', loadComponent: () => import('./features/gps/live-tracking/live-tracking.component').then((m) => m.LiveTrackingComponent) },
      { path: 'trips', title: 'Trip History | Shipper Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trips/:id', title: 'Trip Details | Shipper Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-details/trip-details.component').then((m) => m.TripDetailsComponent) },
      { path: 'wallet', title: 'Wallet | Shipper Portal | TransportSeva', loadComponent: () => import('./features/wallet/wallet.component').then((m) => m.WalletComponent) },
      { path: 'payments', title: 'Payments | Shipper Portal | TransportSeva', loadComponent: () => import('./features/payments/payments.component').then((m) => m.PaymentsComponent) },
      { path: 'reports', title: 'Reports & Analytics | Shipper Portal | TransportSeva', loadComponent: () => import('./features/reports/reports.component').then((m) => m.ReportsComponent) },
      { path: 'documents', title: 'Documents | Shipper Portal | TransportSeva', loadComponent: () => import('./features/documents/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'notifications', title: 'Notifications | Shipper Portal | TransportSeva', loadComponent: () => import('./features/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'support', title: 'Support | Shipper Portal | TransportSeva', loadComponent: () => import('./features/support/support.component').then((m) => m.SupportComponent) },
      { path: 'profile', title: 'Business Settings | Shipper Portal | TransportSeva', loadComponent: () => import('./features/business-settings/business-settings.component').then((m) => m.BusinessSettingsComponent) },
      { path: '**', title: 'Shipper Portal | TransportSeva', component: ComingSoonComponent },
    ],
  },
  {
    path: 'transporter',
    component: ShellComponent,
    canActivate: [setPortalRole('transporter')],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', title: 'Dashboard | Transporter Portal | TransportSeva', loadComponent: () => import('./features/transporter/dashboard/transporter-dashboard.component').then((m) => m.TransporterDashboardComponent) },
      { path: 'load-board', title: 'Load Board | Transporter Portal | TransportSeva', loadComponent: () => import('./features/marketplace/load-board/load-board.component').then((m) => m.LoadBoardComponent) },
      { path: 'load-board/:id', title: 'Load Details | Transporter Portal | TransportSeva', loadComponent: () => import('./features/marketplace/load-details/load-details.component').then((m) => m.LoadDetailsComponent) },
      { path: 'post-load', title: 'Post Load | Transporter Portal | TransportSeva', loadComponent: () => import('./features/marketplace/post-load/post-load.component').then((m) => m.PostLoadComponent) },
      { path: 'my-loads', title: 'My Loads | Transporter Portal | TransportSeva', loadComponent: () => import('./features/marketplace/my-loads/my-loads.component').then((m) => m.MyLoadsComponent) },
      { path: 'applications', title: 'My Applications | Transporter Portal | TransportSeva', loadComponent: () => import('./features/marketplace/applications/applications.component').then((m) => m.ApplicationsComponent) },
      { path: 'requests', title: 'Booking Requests | Transporter Portal | TransportSeva', loadComponent: () => import('./features/marketplace/bookings/bookings.component').then((m) => m.BookingsComponent) },
      { path: 'fleet', title: 'Fleet & Drivers | Transporter Portal | TransportSeva', loadComponent: () => import('./features/fleet/vehicle-list/vehicle-list.component').then((m) => m.VehicleListComponent) },
      { path: 'fleet/drivers', title: 'Fleet & Drivers | Transporter Portal | TransportSeva', loadComponent: () => import('./features/drivers/driver-list/driver-list.component').then((m) => m.DriverListComponent) },
      { path: 'fleet/drivers/:id', title: 'Driver Profile | Transporter Portal | TransportSeva', loadComponent: () => import('./features/drivers/driver-details/driver-details.component').then((m) => m.DriverDetailsComponent) },
      { path: 'fleet/:id', title: 'Vehicle Details | Transporter Portal | TransportSeva', loadComponent: () => import('./features/fleet/vehicle-details/vehicle-details.component').then((m) => m.VehicleDetailsComponent) },
      { path: 'devices', title: 'Device Inventory | Transporter Portal | TransportSeva', loadComponent: () => import('./features/gps/device-inventory/device-inventory.component').then((m) => m.DeviceInventoryComponent) },
      { path: 'devices/:id', title: 'Device Details | Transporter Portal | TransportSeva', loadComponent: () => import('./features/gps/device-details/device-details.component').then((m) => m.DeviceDetailsComponent) },
      { path: 'tracking', title: 'Live Tracking | Transporter Portal | TransportSeva', loadComponent: () => import('./features/gps/live-tracking/live-tracking.component').then((m) => m.LiveTrackingComponent) },
      { path: 'trips', title: 'Trips | Transporter Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trips/:id', title: 'Trip Details | Transporter Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-details/trip-details.component').then((m) => m.TripDetailsComponent) },
      { path: 'wallet', title: 'Wallet | Transporter Portal | TransportSeva', loadComponent: () => import('./features/wallet/wallet.component').then((m) => m.WalletComponent) },
      { path: 'payments', title: 'Payments | Transporter Portal | TransportSeva', loadComponent: () => import('./features/payments/payments.component').then((m) => m.PaymentsComponent) },
      { path: 'reports', title: 'Reports & Analytics | Transporter Portal | TransportSeva', loadComponent: () => import('./features/reports/reports.component').then((m) => m.ReportsComponent) },
      { path: 'documents', title: 'Documents | Transporter Portal | TransportSeva', loadComponent: () => import('./features/documents/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'notifications', title: 'Notifications | Transporter Portal | TransportSeva', loadComponent: () => import('./features/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'support', title: 'Support | Transporter Portal | TransportSeva', loadComponent: () => import('./features/support/support.component').then((m) => m.SupportComponent) },
      { path: 'profile', title: 'Business Settings | Transporter Portal | TransportSeva', loadComponent: () => import('./features/business-settings/business-settings.component').then((m) => m.BusinessSettingsComponent) },
      { path: '**', title: 'Transporter Portal | TransportSeva', component: ComingSoonComponent },
    ],
  },
  {
    path: 'truck-owner',
    component: ShellComponent,
    canActivate: [setPortalRole('truck-owner')],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', title: 'Dashboard | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/truck-owner/dashboard/truck-owner-dashboard.component').then((m) => m.TruckOwnerDashboardComponent) },
      { path: 'load-board', title: 'Load Board | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/marketplace/load-board/load-board.component').then((m) => m.LoadBoardComponent) },
      { path: 'load-board/:id', title: 'Load Details | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/marketplace/load-details/load-details.component').then((m) => m.LoadDetailsComponent) },
      { path: 'applications', title: 'My Applications | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/marketplace/applications/applications.component').then((m) => m.ApplicationsComponent) },
      { path: 'bookings', title: 'Bookings | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/marketplace/bookings/bookings.component').then((m) => m.BookingsComponent) },
      { path: 'vehicles', title: 'My Vehicles | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/fleet/vehicle-list/vehicle-list.component').then((m) => m.VehicleListComponent) },
      { path: 'vehicles/:id', title: 'Vehicle Details | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/fleet/vehicle-details/vehicle-details.component').then((m) => m.VehicleDetailsComponent) },
      { path: 'drivers', title: 'My Drivers | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/drivers/driver-list/driver-list.component').then((m) => m.DriverListComponent) },
      { path: 'drivers/:id', title: 'Driver Profile | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/drivers/driver-details/driver-details.component').then((m) => m.DriverDetailsComponent) },
      { path: 'devices', title: 'Device Inventory | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/gps/device-inventory/device-inventory.component').then((m) => m.DeviceInventoryComponent) },
      { path: 'devices/:id', title: 'Device Details | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/gps/device-details/device-details.component').then((m) => m.DeviceDetailsComponent) },
      { path: 'tracking', title: 'Live Tracking | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/gps/live-tracking/live-tracking.component').then((m) => m.LiveTrackingComponent) },
      { path: 'trips', title: 'Trips | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trips/:id', title: 'Trip Details | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-details/trip-details.component').then((m) => m.TripDetailsComponent) },
      { path: 'wallet', title: 'Wallet | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/wallet/wallet.component').then((m) => m.WalletComponent) },
      { path: 'payments', title: 'Payments | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/payments/payments.component').then((m) => m.PaymentsComponent) },
      { path: 'reports', title: 'Reports & Analytics | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/reports/reports.component').then((m) => m.ReportsComponent) },
      { path: 'documents', title: 'Documents | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/documents/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'notifications', title: 'Notifications | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'support', title: 'Support | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/support/support.component').then((m) => m.SupportComponent) },
      { path: 'profile', title: 'Business Settings | Truck Owner Portal | TransportSeva', loadComponent: () => import('./features/business-settings/business-settings.component').then((m) => m.BusinessSettingsComponent) },
      { path: '**', title: 'Truck Owner Portal | TransportSeva', component: ComingSoonComponent },
    ],
  },
  {
    path: 'driver',
    component: ShellComponent,
    canActivate: [setPortalRole('driver')],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', title: 'Dashboard | Driver Portal | TransportSeva', loadComponent: () => import('./features/driver/dashboard/driver-dashboard.component').then((m) => m.DriverDashboardComponent) },
      { path: 'trips', title: 'Assigned Trips | Driver Portal | TransportSeva', data: { defaultTab: 'active' }, loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trip-history', title: 'Trip History | Driver Portal | TransportSeva', data: { defaultTab: 'completed' }, loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trips/:id', title: 'Trip Details | Driver Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-details/trip-details.component').then((m) => m.TripDetailsComponent) },
      { path: 'pod', title: 'Digital POD | Driver Portal | TransportSeva', data: { defaultTab: 'completed' }, loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'wallet', title: 'Wallet | Driver Portal | TransportSeva', loadComponent: () => import('./features/wallet/wallet.component').then((m) => m.WalletComponent) },
      { path: 'documents', title: 'Documents | Driver Portal | TransportSeva', loadComponent: () => import('./features/documents/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'notifications', title: 'Notifications | Driver Portal | TransportSeva', loadComponent: () => import('./features/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'support', title: 'Support | Driver Portal | TransportSeva', loadComponent: () => import('./features/support/support.component').then((m) => m.SupportComponent) },
      { path: '**', title: 'Driver Portal | TransportSeva', component: ComingSoonComponent },
    ],
  },
  {
    path: 'company',
    component: ShellComponent,
    canActivate: [setPortalRole('company')],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'fleet', title: 'Fleet & Drivers | Company Portal | TransportSeva', loadComponent: () => import('./features/fleet/vehicle-list/vehicle-list.component').then((m) => m.VehicleListComponent) },
      { path: 'fleet/drivers', title: 'Fleet & Drivers | Company Portal | TransportSeva', loadComponent: () => import('./features/drivers/driver-list/driver-list.component').then((m) => m.DriverListComponent) },
      { path: 'fleet/drivers/:id', title: 'Driver Profile | Company Portal | TransportSeva', loadComponent: () => import('./features/drivers/driver-details/driver-details.component').then((m) => m.DriverDetailsComponent) },
      { path: 'fleet/:id', title: 'Vehicle Details | Company Portal | TransportSeva', loadComponent: () => import('./features/fleet/vehicle-details/vehicle-details.component').then((m) => m.VehicleDetailsComponent) },
      { path: 'trips', title: 'Trips | Company Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-list/trip-list.component').then((m) => m.TripListComponent) },
      { path: 'trips/:id', title: 'Trip Details | Company Portal | TransportSeva', loadComponent: () => import('./features/trips/trip-details/trip-details.component').then((m) => m.TripDetailsComponent) },
      { path: 'wallet', title: 'Wallet | Company Portal | TransportSeva', loadComponent: () => import('./features/wallet/wallet.component').then((m) => m.WalletComponent) },
      { path: 'payments', title: 'Payments | Company Portal | TransportSeva', loadComponent: () => import('./features/payments/payments.component').then((m) => m.PaymentsComponent) },
      { path: 'reports', title: 'Reports & Analytics | Company Portal | TransportSeva', loadComponent: () => import('./features/reports/reports.component').then((m) => m.ReportsComponent) },
      { path: 'documents', title: 'Documents | Company Portal | TransportSeva', loadComponent: () => import('./features/documents/documents.component').then((m) => m.DocumentsComponent) },
      { path: 'notifications', title: 'Notifications | Company Portal | TransportSeva', loadComponent: () => import('./features/notifications/notifications.component').then((m) => m.NotificationsComponent) },
      { path: 'support', title: 'Support | Company Portal | TransportSeva', loadComponent: () => import('./features/support/support.component').then((m) => m.SupportComponent) },
      { path: 'profile', title: 'Business Settings | Company Portal | TransportSeva', loadComponent: () => import('./features/business-settings/business-settings.component').then((m) => m.BusinessSettingsComponent) },
      { path: 'staff', title: 'Business Settings | Company Portal | TransportSeva', loadComponent: () => import('./features/business-settings/business-settings.component').then((m) => m.BusinessSettingsComponent) },
      { path: '**', title: 'Company Portal | TransportSeva', component: ComingSoonComponent },
    ],
  },
];
